# Generated by Django 4.2.2 on 2023-07-18 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lodging_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='room_chosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.owner_utility'),
        ),
        migrations.AddField(
            model_name='lodge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lodge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodging_app.lodge'),
        ),
    ]
