# Generated by Django 4.2.2 on 2023-06-28 07:50

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('itemPrice', models.IntegerField()),
                ('item_image', cloudinary.models.CloudinaryField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.categories')),
            ],
            options={
                'db_table': 'items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.IntegerField()),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Owner_Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_table', models.BooleanField(default=False)),
                ('room_number', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'owner_utility',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField()),
                ('is_chef', models.BooleanField()),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_item_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.items')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.order')),
            ],
            options={
                'db_table': 'order_Items',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.user'),
        ),
        migrations.CreateModel(
            name='Lodge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('identity_proof', cloudinary.models.CloudinaryField(max_length=255)),
                ('is_booked', models.BooleanField()),
                ('checkIn', models.BooleanField()),
                ('checkOut', models.BooleanField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.user')),
            ],
            options={
                'db_table': 'lodge',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.items')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.user')),
            ],
            options={
                'db_table': 'cart',
                'managed': True,
            },
        ),
    ]
