# Generated by Django 4.2.2 on 2023-07-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_deliverd',
            field=models.BooleanField(default=False),
        ),
    ]
