# Generated by Django 4.2.2 on 2023-07-18 14:03

from django.db import migrations
import menu_app.manager


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', menu_app.manager.CustomUserManager()),
            ],
        ),
    ]
