# Generated by Django 4.2.2 on 2023-07-19 04:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_utility',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='owner_utility',
            name='image1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owner_utility',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owner_utility',
            name='image3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owner_utility',
            name='image4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owner_utility',
            name='is_booked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='owner_utility',
            name='is_cancelled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='owner_utility',
            name='is_table',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='owner_utility',
            name='number_var',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='owner_utility',
            name='room_number',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='owner_utility',
            name='room_price',
            field=models.IntegerField(blank=True),
        ),
    ]
