# Generated by Django 4.2.2 on 2023-07-10 05:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_cart_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
