# Generated by Django 4.2.2 on 2023-07-11 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_categories_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='orderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_app.order'),
        ),
    ]
