# Generated by Django 4.2.2 on 2023-07-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0005_customuser_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='orderid',
        ),
    ]
