# Generated by Django 4.2.2 on 2023-07-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0005_alter_owner_utility_number_var'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_utility',
            name='room_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
