# Generated by Django 4.2.2 on 2023-07-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0006_remove_customuser_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_place',
            field=models.BooleanField(default=False),
        ),
    ]
