# Generated by Django 4.2.2 on 2023-07-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0008_alter_order_order_deliverd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_deliverd',
            field=models.BooleanField(default=False),
        ),
    ]
