# Generated by Django 4.2.2 on 2023-07-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0009_alter_order_order_deliverd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='create_cart',
            field=models.BooleanField(default=False),
        ),
    ]
