# Generated by Django 4.2.2 on 2023-07-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0011_remove_cart_create_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_created',
            field=models.BooleanField(default=False),
        ),
    ]
