# Generated by Django 4.2.2 on 2023-07-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0012_cart_cart_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='generate_bill',
            field=models.BooleanField(default=False),
        ),
    ]
