# Generated by Django 4.2.2 on 2023-07-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0014_remove_order_order_deliverd_remove_order_order_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sub_orderid',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='sub_orderid',
        ),
        migrations.AddField(
            model_name='order',
            name='order_deliverd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_place',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SubOrder',
        ),
    ]
