# Generated by Django 4.2.2 on 2023-07-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0017_remove_suborder_generate_bill_suborder_orderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suborder',
            old_name='orderid',
            new_name='main_orderid',
        ),
    ]
